site_name: MkDocs Bootswatch Themes


theme:
    name: readthedocs
    
    
nav:
  - Index: index.md
  - Page 1: page1.md
  # 下面代表的是一组页面
  - Page Group:
    - Sub Page 1: subpage/page1.md
    - Sub Page 2: subpage/page2.md
  -About: about.md

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
