site_name: MkDocs Bootswatch Themes


theme:
    name: mkdocs
    
    
nav:
  - Index: index.md
  - Page 1: examples.md
  # 下面代表的是一组页面
  - Page Group:
    - Sub Page 1: sub-dir/sub-page.md



markdown_extensions:
    - toc:
        permalink: '#'
    - admonition
    - def_list
    - mdx_gh_links:
        user: fm1221
        repo: mkdocs-bootswatch

plugins:
    - search
